pyhilo/api.py

Notification registration isn't required for WebSocket registration
Notification services are only used for Android/iOS notification with the Hilo App

Remove unneeded Notification Registration

---

pyhilo/const.py
pyhilo/device/light.py

Ajoute les attributs et les constants nécéssaire pour supporter les lumière RGBW. 
Testé avec une ampoule intelligente de couleur Sylvania A19 Smart+
Modèle : 74933
Je n'ai pas pu testé si le support pour les ampoules non RGB est correcte puisque je n'en possède pas.

Ajout du support pour les ColorBulbs

---

pyhilo/const.py

Mon contrat Hilo venait avec un Outdoor Smart Switch de Jasco. Je l'ai ajouté à la liste de outlet :)
https://byjasco.com/enbrighten-zigbee-plug-in-outdoor-smart-switch-black

Add Jasco 41300 to the outlet list

---

pyhilo/websocket.py

Ajout de deux await pour forcer cleanup_queue à s'exécuter, la coroutine n'était que définie/créée , sans être appelée.

Fix pour dvd-dev/hilo#282

---

pyhilo/api.py

Ajout de "+" comme caractère accepté de mot de passe pour les gens utilisant des mots de passes complexe. Testé en local en changeant mon mot de passe pour y mettre un + et ça fonctionne.
Fix pour dvd-dev/hilo#313 et possiblement dvd-dev/hilo#306 et dvd-dev/hilo#309

Ajout de "+"

---

pyhilo/const.py
pyhilo/devices.py
pyhilo/event.py
pyhilo/websocket.py

Support for new attribute without causing warnings
Support for CCR/CEE (as switches)
Partial Support for 24v thermostat (honeywell / resideo) (as a regular thermostat).. still work to be done 
Support for Floor thermostat (as a regular thermostat) 
Bugfix: Gracefuly handle cases where the websocket client stacks multiple messages in a single receive call 
Bugfix: Gracefuly handle malformed json messages
Wait 5s on websocket reconnect, instead of 1s.

Support new SignalR commands, device types and misc fixes

---

pyhilo/api.py

Dans les caractères parsé par urllib, ça va éviter des auth_errors pour les gens qui ont des caractères spéciaux dans le mot de passe voir dvd-dev/hilo#331

Ajout de caractères spéciaux

---

pyhilo/device/__init__.py

https://github.com/dvd-dev/hilo/issues/310
Set internal state to assumed value (that one just set) to avoid a revert-to-original in the UI. We end up getting the actual value from SignalR later (0 to 10s later).

Issue #310: Fix value reverts back to original value in the UI

---

pyhilo/const.py

Adds supports for bulbs that report as White Bulb, such as Sylvana Smart+.

Add missing device type WhiteBulb

---

pyhilo/const.py

Désolé, j'aurais du l'ajouté hier en même temps que l'autre commit. Au début je pensais l'ajouter dans hilo/const.py, mais finalement puisque c'est une liste de devices je trouvais que ça faisait peut-être plus de sens de le mettre ici pour les regroupés. Je ne l'utiliserai pas dans python-hilo. Donc dites moi si vous trouvez que ça serait mieux dans hilo.
Merci!

Ajout UNMONITORED_DEVICES pour utilitisation dans hilo/sensor.py

---

pyhilo/device/__init__.py

Unknown est un état que HA comprend, c'est la valeur qui est donné aux entité lorsque les données ne sont pas disponible.
Pour l'instant tous les get_value dans Hilo sont spéficiés avec une valeur de 0 pour la valeur par défaut. Donc pour l'instant ce changement n'aura aucun impact. J'ai fait des tests en changeant l'intégration, je vais mettre à jour prochainement.

Changement de la valeur par défault du get_value de None à 'unknown'

---

LICENSE
pyhilo/device/climate.py
pyproject.toml

Problème soulevé dans dvd-dev/hilo#466. Hilo nous a poussé des valeurs nulles par erreur et on dirait que ça reste collé.
Fait une petite logique pour ramasser la valeur des min/max lorsqu'elles existent, sinon si elles sont vides ou = 0 je hard code ça à 5-36 pour inclure les thermostats de plancher.
C'est pas super chic, mais ça devrait nous sortir du trouble.

Fix pour les problèmes de min/max de thermostats

---

.pre-commit-config.yaml
pyhilo/api.py
pyhilo/const.py
pyhilo/util/state.py
pyproject.toml

Ajout d'un lock au fichier hilo_state.yaml pendant l'écriture pour éviter que plus qu'un thread écrive dedans en même temps.
Pourrait possiblement régler dvd-dev/hilo#457

Fix attempt pour issue 457

---

pyhilo/api.py
pyhilo/websocket.py

Plus de 401 pour les ws.
J’ai été un peu brutal sur le refresh_ws de api.py , sinon ça tentait de refresh le deuxième ws avec le endpoint du premier. Je pense que faire une liste ou un dict serait peut être plus simple ensuite mais ça demande quand même un peu de refactor.
Pour ce qui bloquait, il me semble que chaque ws a besoin de son propre token, le shared_token c’est probablement ce qui bloque, j’ai donc modifié pour que les deux soit bien avec leur propre token (facile avec la conf), et je récupère bien l’url.

Keeping the right tokens for every websocket connection

---

README.md

This is to add informations related to what was changed in #242. 
It adds information about the dev environment, dev container and contributors.

Update readme for dev container

---

pyhilo/api.py
pyhilo/const.py
pyhilo/oauth2.py
pyhilo/oauth2helper.py

Move oauth2 flow components from pyhilo to hilo. PyHilo had dependencies to HA, this commit allows a transition to the removal of those dependencies. Once the new HA integration is release we'll be able to remove oauth2.py (AuthCodeWithPKCEImplementation)

Move oauth2 flow components from pyhilo to hilo.

---

.github/workflows/tests.yaml

It's not really helpful to run the lint on the code daily if nothing changes. It's best to just run in on push and on pull_request.
I get an email each day telling me the lint tests are failing.
This will be further more improved once #244 is ready.

Remove scheduled run of lint on github

---

pyhilo/device/__init__.py
pyhilo/device/climate.py

This PR is fixing some lint errors to make it easier to implement #244
Error: pyhilo/device/climate.py:1:1: D400 First line should end with a period
Error: pyhilo/device/climate.py:10:7: D101 Missing docstring in public class
Error: pyhilo/device/climate.py:11:9: ANN204 Missing return type annotation for special method `__init__`
Error: pyhilo/device/climate.py:11:9: D107 Missing docstring in `__init__`
Error: pyhilo/device/climate.py:11:54: FA100 Add `from __future__ import annotations` to simplify `typing.Union`
Error: pyhilo/device/climate.py:12:42: PGH003 Use specific rule codes when ignoring type issues
Error: pyhilo/device/climate.py:16:9: D102 Missing docstring in public method
Error: pyhilo/device/climate.py:20:9: D102 Missing docstring in public method
Error: …

Fix multiple linting error in climate.py

---

pyhilo/__init__.py

This PR is fixing some lint errors to make it easier to implement #244
This also exports __all__ the modules used by Hilo in HASS. 
https://docs.python.org/3/tutorial/modules.html#importing-from-a-package

Fix lint error: PGH004 Use specific rule codes when using `noqa`

---

pyhilo/__init__.py
pyhilo/api.py
pyhilo/device/__init__.py
pyhilo/device/climate.py
pyhilo/device/graphql_value_mapper.py
pyhilo/devices.py
pyhilo/graphql.py

mise en place de la query graphql et du mapping

Graphql query get location

---

pyhilo/const.py
pyhilo/device/__init__.py

python-hilo should not depend on Home Assistant.
Only ./hilo/pyhilo/oauth2.py is left with Home Assistant dependency after this PR.

Remove `homeassistant.const` dependency

---

pyhilo/const.py
pyhilo/graphql.py
pyhilo/util/state.py
pyproject.toml

Fix typo, fix missing await

---

pyhilo/api.py
pyhilo/devices.py
pyhilo/event.py
pyhilo/graphql.py
pyhilo/oauth2helper.py
pyhilo/websocket.py

Adding some docstrings/comments

---

pyhilo/const.py
pyhilo/graphql.py
pyproject.toml

subscribe_to_device_updated: Wrap the calls in except in a nested try/except to make the code more robust so that we don't exit the inifinite loop.

Fix reconnects to gql endpoint after network outage
